config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'posts#index'
  resources :users
  resources :posts, only: %i[new create index]
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :token
  before_create :remember

  validates :name, presence: true
  validates :email, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :posts

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def self.create_digest(string)
    Digest::SHA1.hexdigest string
  end

  def remember
    self.token = User.new_token
    self.remember_digest = User.create_digest(token)
  end

  def forget
    self.remember_digest = nil
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :just_members, only: %i[new create]
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.author = current_user.name
    if @post.save
      flash[:success] = 'New post succefully saved'
      redirect_to posts_path
    else
      flash[:warning] = 'Please, check for mistakes'
      render 'new'
    end
  end

  def index
    @posts = Post.all
  end

  private

  def just_members
    unless logged?
      flash[:danger] = 'You must be a member and logged in to do that'
      redirect_to login_path
    end
  end

  def post_params
    params.require(:post).permit(:title, :body, :author)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email])
    if user&.authenticate(params[:session][:password])
      log_in(user)
      remember(user)
      redirect_to posts_path
    end
  end

  def destroy
    logout
    redirect_to posts_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to posts_path
    else
      redirect_to new_user_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:token] = user.token
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    elsif cookies.signed[:user_id]
      user = User.find_by(id: cookies.signed[:user_id])
      @current_user = user if user&.authenticate(cookies[:token])
    end
  end

  def logged?
    !current_user.nil?
  end

  def logout
    if logged?
      current_user.forget
      cookies.delete(:user_id)
      cookies.delete(:token)
      session.delete(:user_id)
      @current_user = nil
    end
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="#">Only-members project</a>
    
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-light" style="background-color: #e3f2fd;">
  <div class="container">
    <%= link_to "Only members", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", '#' %></li>
        <li><%= link_to "Help", '#' %></li>
        <% if logged? %>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Profile", current_user %></li>   
          <li>
            <%= link_to "Log out", logout_path, method: :delete %>
          </li> 
        <% else %>
          <li><%= link_to "Log in", login_path %></li> 
          <li><%= link_to "Sign Up", new_user_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Add title</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %> 
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 posts">
    <div id="index">
      <div class="create-new-post">
      <% if logged? %>
        <button class="btn btn-success"><%= link_to "Create New Post", new_post_path %></button>
      <% end %>
      </div>
      <% @posts.each do |post| %>
        <div id="post">
            <p id="title"><%= post.title %></p>
          <p id="body"><%= post.body %></p>
          <p id="author">
            Author:
            <% if logged? %>
              <%= post.author %>
            <% else %>
              <%= link_to "You have to log in to know the author", login_path %>
            <% end %>
          </p>
        </div>
      <% end %>
    </div >

  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">       
        <%= form_for(@post) do |f| %>
            <ul>
            <% @post.errors.full_messages.each do |error| %>
            <li><%= error %></li>
            <% end %>
            </ul>
            <p>
            <%= f.label :title %><br />
            <%= f.text_field :title, class: 'form-control'%>
            </p>
            <p>
            <%= f.label :body %><br />
            <%= f.text_area :body, class: 'form-control'%>
            </p>
            <p>
            <%= f.submit "Create post", class: "btn btn-primary" %>
            </p>
            
        <% end %>

app/views/users/new.html.erb
<%= provide(:title,'login') %>
<div class="container">
    <div class="row">
        <div class="col-sm-4"></div>

        <div class="col-sm-4 login-wrap">
            <h1>Log in</h1>
            
            <%= form_for(@user , url: users_path) do |f| %>

            <%= f.label :name, "name" %> <br>
            <%= f.text_field :name , class: "form-control" %> <br>
            <%= f.label :email, "email" %> <br>
            <%= f.email_field :email , class: "form-control" %> <br>

            <%= f.label :password, "password" %> <br>
            <%= f.password_field :password , class: "form-control"  %> <br>


            <%= f.label :password, "confirmation" %> <br>
            <%= f.password_field :password_confirmation , class: "form-control"  %> <br>
            <%= f.submit  "SIGN UP" %><br>
            <span>already a member? <%= link_to "login" , login_path %></span>
            <% end %>
        </div>

        <div class="col-sm-4"></div>
    </div>
</div>